name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust this branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and run Docker container
      run: |
        docker build -t myflaskapp .
        docker run -p 5000:5000 myflaskapp

    # - name: Test your application (if you have tests)
    #   run: |
    #     # Add commands to run your tests here

    # - name: Deploy (if applicable)
    #   # Add deployment steps if you are deploying somewhere

